[package]
name = "dister"
version = "0.1.0"
authors = ["avd <austin.v.davis@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.0.2"
ndarray= "0.12.0"
num = "0.2.0"
itertools = "0.7.8"
byteorder = "1.2.7"
ndarray-parallel = "0.9.0"
ndarray-npy = "0.3.0"
structopt = "0.2"